// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hycpqtsmttceebpivvvj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh5Y3BxdHNtdHRjZWVicGl2dnZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxODgyNDUsImV4cCI6MjA2Mzc2NDI0NX0.e-_yt1OM3EXS9NibG9gqq5y2qgLqlnRU-LhZ-XppiXE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true
  }
});