// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dsypjhxflqdlydurxsoz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRzeXBqaHhmbHFkbHlkdXJ4c296Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxODYxMTgsImV4cCI6MjA2Mzc2MjExOH0.eRoi0omaiJ01VuGPni0_KSw5kGhcSBaZDNkSdhaJnzU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);